import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 01 \u2014 Data Preparation\n",
    "## Descry \u2014 LogoDet-3K, Logo-2K+ & Fashion Product Images\n",
    "\n",
    "**Prerequisites:**\n",
    "- LogoDet-3K unzipped to `training/datasets/logodet3k/`\n",
    "- Logo-2K+ unzipped to `training/datasets/logo2k/`\n",
    "- Fashion Product Images unzipped to `training/datasets/fashion_products/`\n",
    "\n",
    "### Outputs\n",
    "- `brand_logo_split/` \u2014 images per brand from Logo-2K+ (train/val)\n",
    "- `yolo_logo_detection/` \u2014 YOLO detection dataset from LogoDet-3K (all logos = class 0)\n",
    "- `product_category_split/` \u2014 product images per category from fashion dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 1 \u2014 Imports\n",
    "import os\n",
    "import csv\n",
    "import json\n",
    "import shutil\n",
    "import random\n",
    "from pathlib import Path\n",
    "from PIL import Image\n",
    "\n",
    "random.seed(42)\n",
    "\n",
    "TRAINING_DIR = Path(os.getcwd())\n",
    "DATASET_DIR  = TRAINING_DIR / 'datasets'\n",
    "LOGODET_ROOT = DATASET_DIR / 'logodet3k' / 'LogoDet-3K'\n",
    "LOGO2K_ROOT  = DATASET_DIR / 'logo2k' / 'datasetcopy' / 'trainandtest'\n",
    "FASHION_ROOT = DATASET_DIR / 'fashion_products'\n",
    "\n",
    "print(f'LogoDet root: {LOGODET_ROOT}')\n",
    "print(f'Logo2K+ root: {LOGO2K_ROOT}')\n",
    "print(f'Fashion root: {FASHION_ROOT}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 2 \u2014 Target Brands\n",
    "TARGET_BRANDS = [\n",
    "    'Apple', 'Canon', 'Nikon', 'ASUS', 'Bose', 'Casio', 'Rolex',\n",
    "    'Converse', 'Lacoste', 'Timberland', 'TommyHilfiger',\n",
    "    'RalphLauren', 'UnderArmour', 'TheNorthFace', 'Patagonia',\n",
    "    'Oakley', 'LouisVuitton', 'Versace', 'Armani', 'Levis', 'Xiaomi'\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 3 \u2014 Build brand-to-path mapping (LogoDet-3K & Logo-2K+)\n",
    "\n",
    "# -- LogoDet-3K --\n",
    "logodet_paths = {}\n",
    "if LOGODET_ROOT.exists():\n",
    "    for cat_dir in LOGODET_ROOT.iterdir():\n",
    "        if not cat_dir.is_dir(): continue\n",
    "        for brand_dir in cat_dir.iterdir():\n",
    "            if brand_dir.is_dir(): \n",
    "                logodet_paths[brand_dir.name.lower()] = brand_dir\n",
    "\n",
    "logodet_matched = {}\n",
    "for b in TARGET_BRANDS:\n",
    "    for lb, path in logodet_paths.items():\n",
    "        if b.lower() in lb or lb in b.lower():\n",
    "            logodet_matched[b] = path\n",
    "            break\n",
    "\n",
    "print(f\"LogoDet-3K matched {len(logodet_matched)} target brands.\")\n",
    "\n",
    "# -- Logo-2K+ --\n",
    "logo2k_paths = {'train': {}, 'test': {}}\n",
    "if LOGO2K_ROOT.exists():\n",
    "    for split in ['train', 'test']:\n",
    "        split_dir = LOGO2K_ROOT / split\n",
    "        if not split_dir.exists(): continue\n",
    "        for root_cat in split_dir.iterdir():\n",
    "            if not root_cat.is_dir(): continue\n",
    "            for brand_dir in root_cat.iterdir():\n",
    "                if brand_dir.is_dir():\n",
    "                    logo2k_paths[split][brand_dir.name.lower()] = brand_dir\n",
    "\n",
    "logo2k_matched = {}\n",
    "for b in TARGET_BRANDS:\n",
    "    match_train, match_test = None, None\n",
    "    # Remove spaces for comparison e.g., 'ralphlauren' vs 'ralph lauren'\n",
    "    search_term = b.lower().replace(' ', '')\n",
    "    for lb, path in logo2k_paths['train'].items():\n",
    "        lb_clean = lb.replace(' ', '')\n",
    "        if search_term in lb_clean or lb_clean in search_term:\n",
    "            match_train = path\n",
    "            # Find corresponding test dir\n",
    "            match_test = logo2k_paths['test'].get(lb)\n",
    "            break\n",
    "    if match_train:\n",
    "        logo2k_matched[b] = {'train': match_train, 'test': match_test}\n",
    "\n",
    "print(f\"Logo-2K+ matched {len(logo2k_matched)} target brands.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 4 \u2014 Build Brand Classifier Dataset from Logo-2K+\n",
    "BRAND_SPLIT_DIR = DATASET_DIR / 'brand_logo_split'\n",
    "if BRAND_SPLIT_DIR.exists(): shutil.rmtree(BRAND_SPLIT_DIR)\n",
    "\n",
    "total_logo2k_copied = 0\n",
    "for brand, paths in logo2k_matched.items():\n",
    "    for split, src_dir in paths.items():\n",
    "        if not(src_dir and src_dir.exists()): continue\n",
    "        \n",
    "        # Map 'test' to 'val' for consistency with training script\n",
    "        dest_split = 'val' if split == 'test' else 'train'\n",
    "        dest_dir = BRAND_SPLIT_DIR / dest_split / brand\n",
    "        dest_dir.mkdir(parents=True, exist_ok=True)\n",
    "        \n",
    "        for img_path in src_dir.glob('*.*'):\n",
    "            if img_path.suffix.lower() in ['.jpg', '.png', '.jpeg']:\n",
    "                shutil.copy(img_path, dest_dir / img_path.name)\n",
    "                total_logo2k_copied += 1\n",
    "                \n",
    "print(f'Logo-2K+ Brand split done \u2014 {total_logo2k_copied} total images copied.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 5 \u2014 Build YOLO Dataset from LogoDet-3K\n",
    "YOLO_DIR = DATASET_DIR / 'yolo_logo_detection'\n",
    "if YOLO_DIR.exists(): shutil.rmtree(YOLO_DIR)\n",
    "\n",
    "for split in ('train', 'val'):\n",
    "    (YOLO_DIR / 'images' / split).mkdir(parents=True, exist_ok=True)\n",
    "    (YOLO_DIR / 'labels' / split).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "yolo_counts = {'train': 0, 'val': 0}\n",
    "for brand, brand_dir in logodet_matched.items():\n",
    "    txts = list(brand_dir.glob('*.txt'))\n",
    "    random.shuffle(txts)\n",
    "    \n",
    "    splits = {\n",
    "        'train': txts[:int(len(txts)*0.8)], \n",
    "        'val': txts[int(len(txts)*0.8):]\n",
    "    }\n",
    "    \n",
    "    for split_name, files in splits.items():\n",
    "        for txt in files:\n",
    "            img = brand_dir / (txt.stem + '.jpg')\n",
    "            if not img.exists(): img = brand_dir / (txt.stem + '.png')\n",
    "            if not img.exists(): continue\n",
    "            \n",
    "            shutil.copy(img, YOLO_DIR / 'images' / split_name / f'{brand}_{txt.stem}{img.suffix}')\n",
    "            with open(txt) as fin, open(YOLO_DIR / 'labels' / split_name / f'{brand}_{txt.stem}.txt', 'w') as fout:\n",
    "                for line in fin:\n",
    "                    parts = line.strip().split()\n",
    "                    if parts:\n",
    "                        fout.write('0 ' + ' '.join(parts[1:]) + '\\n')\n",
    "            yolo_counts[split_name] += 1\n",
    "\n",
    "print(f\"YOLO dataset: train={yolo_counts['train']} | val={yolo_counts['val']}\")\n",
    "\n",
    "yaml_str = f\"path: {str(YOLO_DIR.resolve()).replace(chr(92), '/')}\\ntrain: images/train\\nval:   images/val\\nnc: 1\\nnames: ['logo']\\n\"\n",
    "with open(YOLO_DIR / 'logo_data.yaml', 'w') as f:\n",
    "    f.write(yaml_str)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 6 \u2014 Build Product Category Split from Fashion Dataset\n",
    "CATEGORY_MAP = {\n",
    "    'shoes':      ['Casual Shoes', 'Sports Shoes', 'Formal Shoes', 'Heels', 'Flats'],\n",
    "    't-shirt':    ['Tshirts'],\n",
    "    'jacket':     ['Jackets'],\n",
    "    'dress':      ['Dresses'],\n",
    "    'handbag':    ['Handbags'],\n",
    "    'watch':      ['Watches'],\n",
    "    'backpack':   ['Backpacks'],\n",
    "    'jeans':      ['Jeans'],\n",
    "    'sunglasses': ['Sunglasses'],\n",
    "    'wallet':     ['Wallets'],\n",
    "    'belt':       ['Belts'],\n",
    "    'cap':        ['Caps'],\n",
    "}\n",
    "\n",
    "style_to_category = {}\n",
    "for target, styles in CATEGORY_MAP.items():\n",
    "    for style in styles:\n",
    "        style_to_category[style] = target\n",
    "\n",
    "CAT_SPLIT_DIR = DATASET_DIR / 'product_category_split'\n",
    "if CAT_SPLIT_DIR.exists(): shutil.rmtree(CAT_SPLIT_DIR)\n",
    "for ds in ('train', 'val', 'test'):\n",
    "    for cat in CATEGORY_MAP.keys():\n",
    "        (CAT_SPLIT_DIR / ds / cat).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "images_by_cat = {c: [] for c in CATEGORY_MAP.keys()}\n",
    "csv_path = FASHION_ROOT / 'styles.csv'\n",
    "img_dir  = FASHION_ROOT / 'images'\n",
    "\n",
    "with open(csv_path, encoding='utf-8', errors='ignore') as f:\n",
    "    reader = csv.DictReader(f)\n",
    "    for row in reader:\n",
    "        article_type = row.get('articleType')\n",
    "        if article_type in style_to_category:\n",
    "            img_id = row.get('id')\n",
    "            target_cat = style_to_category[article_type]\n",
    "            images_by_cat[target_cat].append(f'{img_id}.jpg')\n",
    "\n",
    "print(f'Parsed CSV. Copying images...')\n",
    "\n",
    "total_copied = 0\n",
    "for cat, img_list in images_by_cat.items():\n",
    "    random.shuffle(img_list)\n",
    "    n = min(len(img_list), 2000) # Max 2000 per cat\n",
    "    img_list = img_list[:n]\n",
    "    \n",
    "    splits = {\n",
    "        'train': img_list[:int(n*0.70)],\n",
    "        'val':   img_list[int(n*0.70):int(n*0.90)],\n",
    "        'test':  img_list[int(n*0.90):],\n",
    "    }\n",
    "\n",
    "    copied = 0\n",
    "    for split_name, files in splits.items():\n",
    "        for f in files:\n",
    "            src = img_dir / f\n",
    "            if src.exists():\n",
    "                shutil.copy(src, CAT_SPLIT_DIR / split_name / cat / f)\n",
    "                copied += 1\n",
    "    total_copied += copied\n",
    "    print(f'  {cat}: {copied} images mapped')\n",
    "\n",
    "print(f'\\nCategory split done \u2014 {total_copied} total images copied.')\n",
    "print('\\n✅ Phase 1 complete. Proceed to Run notebooks 02, 03, and 04 for training.')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\Projects\descry\descry\training\01_data_preparation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
